### ISSUE TITLE
Allow to set a download folder when downloading media files

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#200]

**Comment by Oddward** [comment]
+1

I came here to suggest this feature if it wasn't already suggested 🙃, I think it's more than "nice to have". 

Right now the app saves to Downloads which is more like a junk/dump folder IMO since it's the default for things like browsers & some resource directories of other apps like media players, meanwhile I browse a lot of diff media on diff apps and the organization of having their own folders is something I rely on daily.

I browse tonnes of art on twitter (& move files between devices), and harpy seems way better for that than stock twitter, it would be great to save files to a harpy or twitter folder ✨

**Comment by sakuyamaij** [comment]
I think it is better that picture will be saved at /Picture/harpy
Not Download folder
