### ISSUE TITLE
Restore last read position when opening Harpy

### ISSUE THREAD

**Issue by sboulema** [robertodoering/harpy#252]
I would like Harpy to save my last read tweet and upon opening Harpy, load new tweets and restore my scroll position to my last read tweet, so that I can scroll up and read to catch up with all the new tweets.

**Comment by robertodoering** [comment]
Great suggestion, definitely something I want to add!
I planned to implement this when I cache the home timeline. This would make it easy since I can just restore the last `scrollOffset` for the list together with the cached Tweets upon opening the app.

It will take a bit more effort to implement this without caching the list beforehand. I will experiment with it a bit soon and maybe add on it once the timeline gets cached.
