### ISSUE TITLE
Error loading tweets

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#310]
This randomly keeps happening, it seems waiting a couple mins before opening app again fixes it. It seems to happen most when refreshing timeline alot or if you're a person who uses twitter a lot so the timeline keeps refreshing. Hope this is fixed.  ![Screenshot_20210330-153323_Harpy Free.png](https://user-images.githubusercontent.com/3034555/113045925-695b8380-916d-11eb-84cc-f8d72bf92dfb.png)

**Comment by robertodoering** [comment]
This happens when you reach the rate limit. You can refresh 15 times / 15 minutes or open the app up to 7 times in 15 minutes until you reach the limit.
This is due to Twitter limiting requests to their API and it's something we have to live with. In normal use I expect you would rarely run into the limits, though.
