### ISSUE TITLE
Investigate bad scrolling performance in timelines

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#326]
Some users report bad performance & stuttering when scrolling through the timeline, despite having hardware that should be more than capable of rendering the tweets.

Reasons that could cause this issue:
- Devices that set the display frame rate dynamically don't use a high refresh rate in Harpy (e.g. a phone that locks the display to 30fps when idle and goes up to 90fps when in use never switches to higher refresh rates)
  - See: https://github.com/flutter/flutter/issues/35162
- Complex layout calculations & image caching
  - This can cause minor hiccups mostly on lower end hardware
  - Instead of requesting the highest image quality by default, we should instead request a size that matches the layout constrains of the displayed image
  - the 'low performance mode' setting could be used to simplify the layout significantly (instead of just disabling animations and transparency)

**Comment by seriosbrad** [comment]
I noticed this was marked as closed, does this imply that it was fixed at some point?  Because I have terrible scrolling stuttering on a Galaxy S20 FE in both free and pro as of today. I've disabled battery optimization for Haroy, enabled Samsung's "enhanced processing", and tried with both 60Hz and 120Hz.

**Comment by scottiefalkon** [comment]
I'm starting to notice it at times as well on a Pixel 6 Pro.
