### ISSUE TITLE
Ability to see comments beyond an hour ago.

### ISSUE THREAD

**Issue by HorusOwl** [robertodoering/harpy#330]

**Comment by HorusOwl** [comment]
Comments, I mean.

**Comment by robertodoering** [comment]
You can already see comments that are older than 1 hour.
However the way it works right now is more like a workaround - when you open the tweet replies, we do a search for the last 400 replies towards the tweet's author and then filter the result for replies to the tweet you opened.
This obviously doesn't work well if you open older tweets from people that get a lot of replies.

The reason it works like that because the current API doesn't provide a proper endpoint for retrieving tweet replies.
For this to properly be implement we should wait for the new Twitter API to implement an endpoint for that.
See #322
