### ISSUE TITLE
Nord Theme

### ISSUE THREAD

**Issue by awsomemanNever** [robertodoering/harpy#371]
I know that you can add a custom one but without a hex editor, it's really cumbersome. I want to make nord theme a nice and simple predefined color scheme that doesn't require the pro subscription

**Comment by awsomemanNever** [comment]
Now i know you can make a custom theme with harpy pro, but I wanted to include nord as a nice non pro theme

**Comment by awsomemanNever** [comment]
sorry closed this accidently
Could i be assigned to this one? Very easy in my opinion.

**Comment by robertodoering** [comment]
With #282 I plan to improve the theme customization and also allow to set precise color values.
I will also revisit the existing themes and remove the 'phoenix' theme. I will consider to add the nord theme and maybe other popular themes as presets for the pro version, but not for the free version.

I've updated the description of #282 to consider adding the nord theme since it doesn't make much sense to add a pro only theme right now.
