### ISSUE TITLE
More consistent splash screen animation.

### ISSUE THREAD

**Issue by cccClyde** [robertodoering/harpy#376]
Since Android 12 is now in Beta, I think it's time to bring this forward:

On Android 12, all apps are now having a splash screen animation based off app icon, making Harpy's launch animation inconsistent because Harpy already has one.

References:

- [SplashScreen API](https://developer.android.com/about/versions/12/features/splash-screen)
- [Exploring Android 12: Splash Screen](https://joebirch.co/android/exploring-android-12-splash-screen/)

**Comment by robertodoering** [comment]
Thanks for showing me this :)

The current android splash screen is actually just black. Only when flutter gets to draw the first frame do we show the harpy splash screen with the logo animation.

I would like to keep the logo animation since I feel like showing a native splash screen with a static image while we load the initial data would be a setback from the current approach.

However we can show a proper native splash screen for the small duration where flutter hasn't drawn its first frame yet and then transition into the harpy splash screen with the logo animation while we wait for the initial data to load.
