### ISSUE TITLE
Laggy scrolling on some Android devices

### ISSUE THREAD

**Issue by KisenaMiyuki** [robertodoering/harpy#399]
Hi Roberto,

I noticed that on my phone the scrolling seems to lag a little bit (and this problem is hanging around for quite some time tbh).

My phone uses a modified version of Android 11 provided by the manufacturer.

Could it be solved or is it some kind of individual case?

**Comment by robertodoering** [comment]
Hey @KisenaMiyuki 
Recently I haven't heard of anyone having issues with performance.
In the past a lot of users with OnePlus phones were reporting issues, but after some performance improvements those issues had been fixed.

What phone do you have?

You can also try enabling the `performance mode` option in `settings > general`, if you haven't already.
This will remove the animation for the tweet cards and hopefully improve the scrolling performance.

**Comment by KisenaMiyuki** [comment]
I'm using OnePlus 7 Pro.

Performance mode was on when I checked it just now, but switching between on and off doesn't seem to influence anything.

It's only that the scrolling behavior happens a couple of milliseconds after performing the action by finger. Not a big issue anyway, but definitely feels a bit "sticky".

**Comment by orbital247** [comment]
Hi Roberto, firstly really great app, beautiful design and looks great on my Samsung Fold 3 inner screen. I do also have this scrolling issue both on the inner and outer screen. It's like the app is only able to run at 60hz rather than 120hz. I can't fix the refresh rate in the system settings the only setting is 'adaptive' where the phone decides the refresh rate.

![Screenshot_20210828-132839_Settings](https://user-images.githubusercontent.com/89691874/131217883-59f68dbf-3817-4a51-8556-8cdb4e404f07.jpg)

**Comment by robertodoering** [comment]
There have been many flutter updates and performance improvements since this issue had been created.

I have heard positive feedback from users with high refresh rate displays recently and get 5ms - 7ms frame times (~150 - 200 fps) on my 120hz display device myself which lead me to believe that this is issue is either resolved or device specific.

I will close it for now. If this is still an issue pleaes let me know.
