### ISSUE TITLE
Auto open keyboard on tweet

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#485]
An option that lets the keyboard automatically be open when you go tweet would be nice to have to make it quicker

**Comment by robertodoering** [comment]
I want to avoid as much clutter in the settings as possible. I can see that this would be useful for some but I don't think it's worth its own option.
This also shouldn't be the default since there will be people that don't intent to write text and just want to share an image for example.

Because of that I will leave it as it is, sorry!

**Comment by dnestico** [comment]
Ah understandable
