### ISSUE TITLE
Add additional fallback fonts

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#495]
I titled it add more fonts but maybe somehow make harpy convert the unreadable tweet font to something different if that makes sense?.. Or I guess just try and add more fonts for the future please that twitter can already convert.

![Screenshot_20211204-234225~2.png](https://user-images.githubusercontent.com/3034555/144733962-f6d6b83d-2dc4-46c8-8e79-05f4a240e2e1.png)

**Comment by robertodoering** [comment]
We can try to download and cache more fallback fonts on app start (I don't want to bundle them with the apk because it would blow up the size significantly)

At the moment we use OpenSans as the default body font for the text in a tweet and use NotoSans as a fallback because it covers a bigger character range. If there are still unknown characters your system will look for installed fonts that cover the character.
If no font is installed then you see the box in the screenshot.

Here is the text in the screenshot for testing purposes:
`ɢᴀᴍᴇ ʜɪɢʜʟɪɢʜᴛs | @ ᴍɪɴ | 𝟷𝟸.𝟶𝟺.𝟸𝟷`

**Comment by dnestico** [comment]
Just another example
![Screenshot_20220122-201340.png](https://user-images.githubusercontent.com/3034555/150660822-b69978a0-94b2-4a07-8ded-27254db263f1.png)

**Comment by robertodoering** [comment]
With the next update harpy will come with updated NotoSans fonts that include a lot more glyphs which should cover those characters and display them properly.

Please let me know if you find more in the future (with a link to the tweet if possible)

**Comment by dnestico** [comment]
Can't wait for the next update! Based off everything you recently marked as completed it seems like it's a big one! 👀
