### ISSUE TITLE
F-droid Release 

### ISSUE THREAD

**Issue by onkoe** [robertodoering/harpy#503]
Hi, any plans for an F-droid release? I know that the app is still in beta, but I'm currently not using any Google services on my phone so I can't get the app. Would compilation be my best option? If so, could someone explain what the Twitter "keys" mean when building? Thanks!

**Comment by robertodoering** [comment]
Unfortunately I won't be able to publish harpy on F-droid, so your best bet is to compile it manually.
Twitter keys refer to the Twitter api key and secret that you get after applying for access to the Twitter api.

You can follow the detailed instructions here: https://github.com/robertodoering/harpy/wiki/Twitter-key-setup
Let me know if something isn't clear and you need advice

**Comment by proletarius101** [comment]
> Twitter keys refer to the Twitter api key and secret that you get after applying for access to the Twitter api..

yes. but they are clear text in your apk...

**Comment by Poussinou** [comment]
@robertodoering If your Twitter keys already are in the source code, we can build this app for F-Droid.

Otherwise, could you please attach the apk in the [releases section](https://github.com/robertodoering/harpy/releases) for each new versions (like Shitter [does](https://github.com/nuclearfog/Shitter/releases) for example) ? It would allow people without Google services (like me) to download your app. Thank you !

**Comment by andsofine** [comment]
any updates?
