### ISSUE TITLE
Draw tweet replies independently

### ISSUE THREAD

**Issue by Goooler** [robertodoering/harpy#513]
There are lags on timeline after 0.8.2 version.

https://user-images.githubusercontent.com/10363352/147851595-551ab17d-d07b-4606-bac0-d0d516ccd9a7.mp4

**Comment by Goooler** [comment]
Seems happens on the showing of the thrid item ？

**Comment by mld9401** [comment]
i can confirm, i am also facing a terrible lag.

**Comment by Goooler** [comment]
> i can confirm, i am also facing a terrible lag.

From 0.8.2？I remembered 0.8.1 without this issus.

**Comment by robertodoering** [comment]
@Goooler 
As you suspected, the dropped frames happen due to the rendering of the 3rd tweet.
The single tweet card contains the parent tweet and all replies and replies of replies of the tweet (i.e. a long 'reply-chain' or 'thread' of tweets). Harpy builds all decendants of a single tweet at once and thus flutter has to do the layout for this long chain of tweets in one frame, which causes this lag spike.

This isn't related to the latest update but has been an issue before as well.

We can fix this by drawing the tweet cards independently, even if they are replies to other tweets in the list.

**Comment by mld9401** [comment]
> > i can confirm, i am also facing a terrible lag.
> 
> From 0.8.2？I remembered 0.8.1 without this issus.

i didn't try 0.8.1 , i am on 0.8.2 and it lags a lot while scrolling.

**Comment by robertodoering** [comment]
@mld9401 
I assume this is independent from this issue. Can you create a new issue and add some more information (device, android version) and preferably a video?

**Comment by mld9401** [comment]
> @mld9401 I assume this is independent from this issue. Can you create a new issue and add some more information (device, android version) and preferably a video?

i have opened a new issue
https://github.com/robertodoering/harpy/issues/516#issue-1091902396
