### ISSUE TITLE
UI lags while scrolling

### ISSUE THREAD

**Issue by mld9401** [robertodoering/harpy#516]
Sometimes, i have some lags while scrolling on timeline and between lists.

> Device : POCO X3 NFC
> Android version : 12 (PixelExperience custom ROM)
> Harpy version : 0.8.2

https://user-images.githubusercontent.com/15183134/147861168-1649244a-702a-474a-9a25-942a5fe50756.mp4

**Comment by robertodoering** [comment]
Thanks for reporting the issue @mld9401 

By the looks of it the dropped frames are simply due to the hardware not being powerful enough for flutter to draw frames fast enough.

You can go to `settings > general` and enable `performance mode` to disable the card animations when scrolling.
Also make to set `settings > media > tweet image quality` to `never use best quality` for the best performance.

**Comment by mld9401** [comment]
After enabling performance mode and setting image quality to "never use best quality", it's better now, but there is still some lag sometimes.

**Comment by robertodoering** [comment]
Good to know that it's better. Unfortunately I can't do much to improve performance further without compromising the look and feel of the app, which I want to prioritize.
Generally performance will only improve in the future as flutter gets faster. Compared to 1 year ago, performance has improved significantly.
