### ISSUE TITLE
Implement twitter communities

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#534]
Would be cool if you could add Twitter communities to harpy.

**Comment by robertodoering** [comment]
I've never heard of that before but if I understand it correctly it's basically a closed off space to tweet in which you have to be invited to, right?

Currently there doesn't seem to be any way to implement communities in harpy as there aren't any endpoints for in in their api afaik, so I will mark this issue as blocked until they allow 3rd party apps to implemement it.

Btw, since it seems that people have to be invited to join communities, if someone has the ability to invite @harpy_app to any community that would be nice for testing purposes.Btw, since it seems that people have to be invited to join communities, if someone has the ability to invite @harpy_app to any community that would be nice for testing purposes.

**Comment by dnestico** [comment]
Ah I see, I thought twitter would have implemented communities in their API by now but its more of a nice to have feature for me, not a must! And also I can't invite you to a community because your DMs are closed so if you temporarily open them I should be able to because DMs are basically links sent through DMs and you accept there.

**Comment by robertodoering** [comment]
@dnestico I just followed you, would it work now?

**Comment by dnestico** [comment]
Check your DMs 👀

**Comment by robertodoering** [comment]
Thank you :)
