### ISSUE TITLE
Bug reports 

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#541]
Is there a possibility to put bug reporting or feedback inside harpy?

It'll make more people willing to report something or give brilliant ideas instead of coming to github which is a bit confusing and rejecting to someone who doesn't have experience with it.

**Comment by robertodoering** [comment]
@FerasK0 
The preferred way for feedback is GitHub. Alternatively users can also find my email in the about screen, which is what most users use to send me feedback and suggestions.

I considered a simple in-app dialog where users can directly send a message to me. However this has a big disadvantage because I can't get back to them easily, unless I ask them to specify their email but that is more trouble for what it's worth.

I think feedback through GitHub and email is more than enough for me, especially because I already spend a lot of time handling those.

**Comment by FerasK0** [comment]
Soo it won't be a thing even in the far future? :/

**Comment by robertodoering** [comment]
I don't see any benefit from it, so I won't plan it for now.
Maybe this will change in the future, though.
