### ISSUE TITLE
Instagram app

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#552]
I really love the design of harpy and think it would be awesome if you made an Instagram client with some extra features and a similar design to harpy.

**Comment by scottiefalkon** [comment]
Didn't you have a Reddit app at one point? I'd love to see that brought
back. And their API isn't near a as restrictive.

**Comment by dnestico** [comment]
He had a reddit app? Wow

**Comment by scottiefalkon** [comment]
He'd have to confirm. But, I'm almost certain.

**Comment by robertodoering** [comment]
I haven't worked on a reddit up before, no. But I could consider working on a reddit client in the future - not anytime soon though since I want to keep working on harpy and spend the little free time that I have on it.

I don't think I'll ever work on an instagram app since I don't use it myself, sorry!

Btw the [discussions](https://github.com/robertodoering/harpy/discussions) are probably a better place for this kind of ideas / requests :)

**Comment by dnestico** [comment]
Ah I see, I'd defenitley use the reddit client if you ever made one.
