### ISSUE TITLE
Keep filters option button visible on all pages

### ISSUE THREAD

**Issue by Luke-L** [robertodoering/harpy#565]
Please return the filters button to pages like viewing an account! I love the new filtering options but it's so annoying to go back to the home page to change it each time.

Also, I shouldn't have to scroll back to the very top to see the timeline filters. Would be better to keep the button in line with the timeline feeds at the top

**Comment by robertodoering** [comment]
The filter for the user was always used for the user timeline, so it has been moved from the app bar to the user timeline. This is preferred because the filter is used explicitly for the user timeline (and not for example the likes timeline).

Also this way it's uniform with other timeline filters (home timeline / list timelines), which both have their filter at the top of the timeline.

I like to have the filter at the top of the timeline and I would be surprised if that is an issue since changing the timeline doesn't happen too frequently. Having to scroll to the top to reach the timeline actions is not an issue in my opinion.
