### ISSUE TITLE
Add Tweet Bookmarks (2)

### ISSUE THREAD

**Issue by Edodaddo** [robertodoering/harpy#566]
I read that in the past Twitter didn't give any API for bookmarks but that with the new API v2.0 things could have changed (reference: #361). 

My question is: have things changed? Would it be possible to add the "bookmarks"  section now?

**Comment by robertodoering** [comment]
Bookmarks have not yet been implemented to their API, but it is planned.
You can see the current status here: https://trello.com/b/myf7rKwV/twitter-developer-platform-roadmap

It is under the 'Nesting' column, which includes

> "Ideas and items we’re exploring, but haven’t started to work on yet."

Either way harpy first has to support the API v2.


In the future when asking for an update, please prefer to add a comment in the existing issue (#361), I will close this one since it's a duplicate.

**Comment by dnestico** [comment]
Thanks for sharing the Trello board I'm defenitley gonna star it and keep an eye on it every so often!

**Comment by Edodaddo** [comment]
Thank you so much for this answer, I just want to tell you that I bought Harpy Pro for your immense kindness and the beauty of your app. Keep it up, I can't wait for the app to arrive on iOS too! :)

**Comment by robertodoering** [comment]
Thanks a bunch! I'm glad you like harpy :)
