### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by xswordcarsh** [robertodoering/harpy#572]
Increase scroll sensitivity on the media tab, fully disable animations, reduce sensitivity on swiping to another tab, implement better toast (using built in android one is still better imo) or just make it show a notification for downloads. Also could use a better caching of the posts and images.

I'm not really a programmer so idk about the terms, pls spare me.

**Comment by robertodoering** [comment]
Thanks for the suggestions!

A native notifications for downloads will come very soon, I've been working on that recently.

> fully disable animations

You can disable some animations by enabling the `general > performance mode`

I'll note down your suggestions and close this issue. For further feedback and ideas feel free to open a [discussion](https://github.com/robertodoering/harpy/discussions) instead of an issue.
