### ISSUE TITLE
Heavy chugging when switching tabs

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#600]
### Issue description 
Sometimes when switching between tabs, you face some chugging and lagging in animations and transitions and also frame dropping.

---
### Expected behavior
Nothing except smooth performance.

---
### Steps to reproduce
Can't find a consistent way to reproduce, but generally it's like this:
1. Go to Home tab
2. Scroll for a bit either up or down
3. Swipe to media tab to right
4. Swipe back while scrolling 
5. Go to Menu tab
6. swipe back to home
7. See error
(All has to be in close in time)

---
### OS Version.

- Android 10
- Samsung Note 9 - Exynos
- February 1 Security Patch
- Harpy Free & Pro 0.8.4+1 and previous versions too

Notes:
Have seen this problem multiple times before since 0.8.0 or 0.8.1 not sure tho but didn't want to report it till i knew what's causing it.

**Comment by robertodoering** [comment]
Thanks for the issue!
This is fixed in this PR #587. With those changes the tab content doesn't get rebuilt every time you switch to it, which prevents dropping those precious frames.

I'll be a bit until those changes go live because we are changing and improved just about everything, but the result will be great :)

**Comment by FerasK0** [comment]
Great! I thought no one knew or reported it.
Will be waiting for that massive technical upgrade, it'll make the app more efficient and faster than ever.
