### ISSUE TITLE
Improve image fetching strategy

### ISSUE THREAD

**Issue by batman-846** [robertodoering/harpy#603]
I have an issue where pictures don't always load in my timeline.  I say this happens to about 50% of the time.  I know it isn't a connection issue, I have this problem on various networks and on cellular.

![Screenshot_20220313-120010_harpy](https://user-images.githubusercontent.com/101524127/158080146-64edde22-84bc-41b1-9884-42991ea01493.jpg)

**Comment by robertodoering** [comment]
Thanks for reporting the issue.

Currently when the image failed to load once (e.g. due to a temporary connection issue) the error placeholder will be built.

I've made some changes so that we now try to fetch the image up to 5 times if it fails. Only then we give up and build the error placeholder. This should prevent you from seeing the error widget frequently if you have temporary connection issues.

The changes are on #587 and will go live with the next update (0.9.0)

**Comment by Jnss98b** [comment]
> Thanks for reporting the issue.
> 
> Currently when the image failed to load once (e.g. due to a temporary connection issue) the error placeholder will be built.
> 
> I've made some changes so that we now try to fetch the image up to 5 times if it fails. Only then we give up and build the error placeholder. This should prevent you from seeing the error widget frequently if you have temporary connection issues.
> 
> The changes are on #587 and will go live with the next update (0.9.0)

Idk if this is included in your fix but you can also add a button in the drop down menu to manually fetch the image too so that they don't have to restart the app when needed
