### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#604]
Welp, looks like authentication issues are back..

I was getting 403 unknown errors when trying to like a tweet so I logged out and now it's not letting me log back in.

![Screenshot_20220314-075019.png](https://user-images.githubusercontent.com/3034555/158166513-64a0c798-0639-42bd-893e-9439b7c22f8d.png)

**Comment by robertodoering** [comment]
Twitter has suspended the API key again :/
They don't respond to support tickets and I have no information as to why it gets suspended, just a message that it 'violated Twitter Rules and policies'.

I'll try to contact them again and in the meantime push an update with a different key. Hopefully it'll get sorted out.

I also tagged them in a tweet, maybe someone at Twitter's support will see it that way :crossed_fingers: 
https://twitter.com/harpy_app/status/1503347427415310341

**Comment by dnestico** [comment]
Wow that's crazy, I wonder what "rules" harpy could've violated somehow.

I hope they see it and sort this out for good. 👍

**Comment by robertodoering** [comment]
Update with a new key is available now on the Play Store (thankfully this time it went through the review rather quickly).
It's still using a v2 key but this time it's created for the @harpy_app account (rather than my personal account). I also tried to be more descriptive in the usage description for the key to hopefully avoid having it suspended again.

**Comment by patster98** [comment]
Hi I'm facing the issue still with this new update, every once in a while I get logged out automatically and then I have to delete the app and reinstall in order to being able to log back in
