### ISSUE TITLE
Cache / save likes

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#620]
Due to the annoying rate limit that nothing can be done about unfortunately, maybe it could be possible to cache/save the like so we don't get the annoying rate limit error and after the rate limit lifts or whatever the app will look at the cached/saved likes and like it

Not necessary of course but nice to have since I can barley ever like tweets lol

**Comment by robertodoering** [comment]
That won't work in practice unfortunately because likes would just get accumulated and pushed in an endless queue.

The only way to prevent rate limits for users is for the user to use their own API keys - which you can do now by compiling the app yourself or in the future when you can enter your own API key.

**Comment by dnestico** [comment]
Ah I see damn, well I will defenitley enter my own API key in the future forsure 👍

**Comment by robertodoering** [comment]
Yeah, that'll be the best way to work around the api limitations for sure :)
