### ISSUE TITLE
Crash when accessing Twitter link setting

### ISSUE THREAD

**Issue by monee121** [robertodoering/harpy#739]
### Bug description 

The app crashes and closes when I go into settings and attempt to access setting to "open Twitter links" 

---
### Expected behavior

The setting should open so I can choose what I want to do with Twitter links 

---
### Steps to reproduce

1 - open app
2 - click on menu button
3 - choose "settings" 
4 - choose "open Twitter links" 

---

Samsung S22+ running Android 12
Harpy Pro version 0.9.7

**Comment by monee121** [comment]
https://user-images.githubusercontent.com/105255608/183298953-e93f412a-b282-4fe0-9a1b-245813461fad.mp4

Here is screen record of the issue

**Comment by robertodoering** [comment]
Turns out trying to open the 'open by default' app settings page to enable the Twitter urls causes the app to crash on Samsung phones. Now as a workaround we open the 'apps that can open links' settings page and the user has to navigate to harpy themselves to enable the twitter urls.

Thanks for reporting the issue!

**Comment by monee121** [comment]
Thanks so much!!!
