### ISSUE TITLE
Please add option to remain at current tweet in timeline when manually refreshing

### ISSUE THREAD

**Issue by MehBlorg** [robertodoering/harpy#768]
When I refresh my timeline it jumps to the top, to the latest tweet. I have to scroll back down to the last one I read (if I can even find it) so I can start scrolling up and read the ones that just refreshed in. It's a pain.

One way to address this would be to remain on current tweet when I hit refresh.  _TwitPane_ app does that and something else cool where it compacts a number of tweets behind an ellipsis (...) and expands them when the ellipsis is tapped. Really helpful for first read of the day (to see what happened the night before). Makes it simple to read as many or as few missed tweets as you like. Not suggesting you steal that of course, but it's really cool idea and maybe something to build off of here?

**Comment by monee121** [comment]
I agree!  I really hate refreshing the TL sometimes because I know I will lose my place.  That means I don't know how far down to go in order to then scroll up and look at tweets in order.  I also use Fenix for twitter and it refreshes the TL without jumping to the top.  It does have a color slider which turns blue when there are new tweets loaded so you can see how far you are from the top.

**Comment by dnestico** [comment]
There is already an issue for this. Also you can set this already, but currently only at app startup. #267

**Comment by robertodoering** [comment]
Thanks @dnestico! Will close this issue as it is a duplicate
