### ISSUE TITLE
Get harpy running on linux

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#783]
Development will be a lot nicer if no android emulator is required.
Right now the login webview won't work on desktop so an alternative way of logging in for development might be an easy workaround.

**Comment by robertodoering** [comment]
@MitsuhaKitsune 
This issue is related to running harpy natively on linux, not on an android emulator.

Do you have a twitter api key set up? You can read the [setup guide](https://github.com/robertodoering/harpy/wiki/Project-setup-for-building-harpy) for help on getting started with building the project.

**Comment by MitsuhaKitsune** [comment]
@robertodoering Yes I know and it's a good idea, just trying to say that the login workarround help to develop on Android too, because ask for elevated access to login.

Yes, I have essential access to Twitter API and it's configured properly, but when I try to login:

`I/flutter (25427): {"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve","code":453}]}`

As I see, it's the unic endpoint that need apply for Elevated access, with a login workarround we can bypass this endpoint and start to contribute without wait for Twitter access response.

**Comment by robertodoering** [comment]
I see what you mean now, however this workaround implies that you log into Twitter outside of harpy and provide the auth token when building to bypass the login - a twitter api key with elevated access will still be required.

If you want to work on harpy but don't have elevated access, shoot me an email and I can give you some test credentials

**Comment by VexfulNiko** [comment]
I have linux so I'm happy about this one personally.
